{% set name = "perl-config-simple" %}
{% set version = "4.59" %}
{% set sha256 = "cb78a975ad8463f992f35f392227aaf188d533c9092373742b3c2bb592781054" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/S/SH/SHERZODR/Config-Simple-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0
  script:
    - perl Makefile.PL INSTALLDIRS=vendor NO_PERLLOCAL=1 NO_PACKLIST=1
    - make
    - make test
    - make install VERBINST=1

requirements:
  build:
    - make
  host:
    - perl
    - perl-extutils-makemaker
  run:
    - perl

test:
  imports:
    - Config::Simple

about:
  home: https://metacpan.org/dist/Config-Simple
  license: GPL-1.0-or-later OR Artistic-1.0-Perl
  license_family: OTHER
  summary: simple configuration file class
  license_file:
    - {{ environ["PREFIX"] }}/man/man1/perlartistic.1
    - {{ environ["PREFIX"] }}/man/man1/perlgpl.1

extra:
  recipe-maintainers:
    - cbrueffer
